# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - add_ssh_keys:
          fingerprints:
            - "5c:29:7b:ea:3e:36:b6:2f:6a:57:82:a7:92:63:bf:69"
      - run: 
          name: "npm run deploy"
          command: |
            git config --global user.email "hughr2005@gmail.com"
            git config --global user.name "Hugh Rawlinson"
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run deploy
            fi  
