version: 2.0

jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: yarn
      - run: yarn run build
      - add_ssh_keys:
          fingerprints:
            - "5c:29:7b:ea:3e:36:b6:2f:6a:57:82:a7:92:63:bf:69"
      - deploy:
          command: |
            git config --global user.email "hughr2005@gmail.com"
            git config --global user.name "Hugh Rawlinson"
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              yarn run deploy
            fi
